language: node_js
node_js:
    - node
    - '8'
cache:
    apt: true
    directories:
        - node_modules
        - themes
before_install:
- npm install -g hexo-cli
- openssl aes-256-cbc -K $encrypted_2b0aa9dcbfdc_key -iv $encrypted_2b0aa9dcbfdc_iv -in travis.key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
# 修改本机 ssh 配置，防止秘钥认证过程影响自动部署
- mv -fv .travis/ssh-config ~/.ssh/config
- git config --global user.name "CharlesCliff"
- git config --global user.email "1150026521@qq.com"
# 赋予自动部署脚本可执行权限
- chmod +x .travis/deploy.sh
install:
    - npm install
    - if [ ! -d "themes/next" ]; then git clone git@github.com:CharlesCliff/hexo-theme-next.git themes/next; fi

script:
    - hexo clean
    - hexo g
after_success:
    - .travis/deploy.sh
env:
    global:
        - GH_REF: github.com/CharlesCliff/CharlesCliff.github.io
addons:
  ssh_known_hosts:
  - github.com
  - gitee.com
  - charlescliff.com
# 只监听 source 分支的改动
branches:
  only:
  - hexo
